version: '3.4'

services:
  # Inventory Microservice
  eshop.inventory.database:
    image: mongo

  eshop.inventory.api:
    image: ${DOCKER_REGISTRY-}eshopinventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/EShop.Inventory.API/Dockerfile

  # Shopping Cart Microservice
  eshop.cart.database:
    image: redis:alpine

  eshop.cart.api:
    image: ${DOCKER_REGISTRY-}eshopcartapi
    build:
      context: .
      dockerfile: Services/Cart/EShop.Cart.API/Dockerfile

volumes:
  inventory_data:
