version: '3.4'

services:
  # Portainer Dashboard
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes: 
      -  /var/run/docker.sock:/var/run/docker.sock
      -  portainer_data:/data

  # Inventory Microservice
  eshop.inventory.database:
    container_name: eshop.inventory.database
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      -  inventory_data:/data/db

  eshop.inventory.api:
    container_name: eshop.inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://eshop.inventory.database:27017"
    depends_on:
      - eshop.inventory.database
    ports:
      - "10000:80"

  # Shopping Cart Microservice
  eshop.cart.database:
    container_name: eshop.cart.database
    restart: always
    ports:
      - "6379:6379"

  eshop.cart.api:
    container_name: eshop.cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:ConnectionString=eshop.cart.database:6379"
    depends_on:
      - eshop.cart.database
    ports:
      - "10001:80"

