version: '3.4'

services:
  # Portainer Dashboard
  portainer:
    image: portainer/portainer-ce

  # Inventory Microservice
  eshop.inventory.database:
    image: mongo

  eshop.inventory.api:
    image: ${DOCKER_REGISTRY-}eshopinventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/EShop.Inventory.API/Dockerfile

  # Shopping Cart Microservice
  eshop.cart.database:
    image: redis:alpine

  eshop.cart.api:
    image: ${DOCKER_REGISTRY-}eshopcartapi
    build:
      context: .
      dockerfile: Services/Cart/EShop.Cart.API/Dockerfile

  # Voucher Microservice
  eshop.voucher.database:
    image: postgres

volumes:
  inventory_data:
  portainer_data:
  voucher_data:
