version: '3.4'

services:
  # Portainer Dashboard
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes: 
      -  /var/run/docker.sock:/var/run/docker.sock
      -  portainer_data:/data

  # Inventory Microservice
  eshop.inventory.database:
    container_name: eshop.inventory.database
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      -  inventory_data:/data/db

  eshop.inventory.api:
    container_name: eshop.inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://eshop.inventory.database:27017"
    depends_on:
      - eshop.inventory.database
    ports:
      - "10000:80"

  # Shopping Cart Microservice
  eshop.cart.database:
    container_name: eshop.cart.database
    restart: always
    ports:
      - "6379:6379"

  eshop.cart.api:
    container_name: eshop.cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:ConnectionString=eshop.cart.database:6379"
    depends_on:
      - eshop.cart.database
    ports:
      - "10001:80"

  # Voucher Microservice
  eshop.voucher.database:
    container_name: eshop.voucher.database
    restart: always
    environment:
        - POSTGRES_USER=eshop_voucher_db_admin
        - POSTGRES_PASSWORD=85136c79cbf9fe36bb9d05d0639c70c265c18d37
        - POSTGRES_DB=eshop_voucher_db
    ports:
      - "5432:5432"
    volumes:
      - voucher_data:/var/lib/postgresql/data/
  
  eshop.voucher.api:
    container_name: eshop.voucher.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=eshop.voucher.database;Port=5432;Database=eshop_voucher_db;User Id=eshop_voucher_db_admin;Password=85136c79cbf9fe36bb9d05d0639c70c265c18d37;"
    depends_on:
      - eshop.voucher.database
    ports:
      - "10002:80"

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
        - PGADMIN_DEFAULT_EMAIL=eshop_voucher@eshop.com
        - PGADMIN_DEFAULT_PASSWORD=85136c79cbf9fe36bb
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
